bundles:
  - 4
files:
  - source: '*.strings'
    ignore:
      - AppShortcuts
      - InfoPlist
    translation: /Sources/CasaZurigol10n/Resources/%two_letters_code%.lproj/Localizable-crowdin.strings
