name: Create PR for SwiftGen Changes

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/create_PR_with_swiftgen.yml"
      - "Sources/CasaZurigol10n/Resources/**"

permissions:
  contents: write
  pull-requests: write

jobs:
  create-swiftgen-pr:
    runs-on: macos-latest

    steps:
      - name: Install SwiftGen
        run: |
          brew install swiftgen

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: swiftgen-update
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Reset swiftgen-update branch
        run: |
          git fetch origin main:main
          git reset --hard main

      - name: Run SwiftGen
        run: |
          swiftgen config run

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: swiftgen-update
          base: main
          title: "Update generated files via SwiftGen"
          body: "This PR updates the generated files using SwiftGen."
          labels: generated-files
          reviewers: lucaArchidiacono
          assignees: lucaArchidiacono
          sign-commits: true
