name: Create PR for SwiftGen Changes

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/create_PR_with_swiftgen.yml'
      - 'Sources/CasaZurigol10n/Resources/**'

permissions:
  contents: write

jobs:
  create-swiftgen-pr:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install SwiftGen
      run: |
        brew install swiftgen

    - name: Run SwiftGen
      run: |
        swiftgen config run

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Add changes to new branch
      run: |
        git add -A
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git checkout -B swiftgen-update
          git commit -m "Update generated files via SwiftGen"
          git push origin swiftgen-update || (echo "Push failed" && exit 1)
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        branch: swiftgen-update
        base: main
        title: "Update generated files via SwiftGen"
        body: "This PR updates the generated files using SwiftGen."
        labels: generated-files
