name: Update PR with SwiftGen Changes

on:
  pull_request:
    branches:
      - '*'
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  contents: write

jobs:
  update-pr-with-swiftgen:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Install SwiftGen
      run: |
        brew install swiftgen

    - name: Run SwiftGen
      run: |
        swiftgen config run

    - name: Configure Git
      run: |
        git config --global user.name 'GitHub Actions Bot'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

    - name: Add and commit changes
      run: |
        git add -A
        if !git diff --staged --quiet; then
          git commit -m "Update generated files via SwiftGen"
          git push --force origin ${{ github.ref }}
        fi

