name: Update PR with Generated Swift Code
on:
  pull_request:
    branches:
      - "*"
    types:
      - opened
      - edited
      - reopened
      - synchronize

permissions:
  contents: write

jobs:
  update-pr-with-generated-code:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Generate Swift code
        run: |
          sh l10n.sh compileToSwift \
            --input-dir ./Sources/CasaZurigol10n/Resources/en.lproj \
            --ignore "AppShortcuts.strings" \
            --output ./Sources/CasaZurigol10n/Generated/Localization+Generated.swift

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email '41898282+github-actions[bot]@users.noreply.github.com'

      - name: Add and commit changes
        run: |
          git add -A
          if git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update generated Swift localization code"
            git push origin HEAD:${{ github.head_ref }}
          fi
